name: Reusable Semantic Release Workflow

on:
  workflow_call:
    inputs:
      releaserc:
        description: releaserc configuration file
        required: false
        type: string
        default: ./.releaserc.json
    outputs:
      release_created:
        description: "Whether a release was created"
        value: ${{ jobs.semantic-release.outputs.release_created }}
      new_tag:
        description: "Tag of the release created"
        value: ${{ jobs.semantic-release.outputs.new_tag }}
      release_notes:
        description: "Release not of the release created"
        value: ${{ jobs.semantic-release.outputs.release_notes }}

permissions:
  contents: read

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Create .releaserc.json file
        run: |
          echo '{
            "plugins": [
              "@semantic-release/commit-analyzer",
              "@semantic-release/git",
              "@semantic-release/release-notes-generator"
              ] }' > .releaserc.json


      - name: Semantic Release
        id: create_release
        uses: cycjimmy/semantic-release-action@v6
        with:
          semantic_version: 24.0.0

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Github Release
        uses: softprops/action-gh-release@v2.4.2
        if: ${{ steps.create_release.outputs.new_release_published == 'true' }}
        with:
          tag_name: ${{ steps.create_release.outputs.new_release_git_tag }}
          body: ${{ steps.create_release.outputs.new_release_notes }}
      - name: Set outputs
        id: set_outputs
        run: |
          echo "release_created=${{ steps.create_release.outputs.new_release_published }}" >> $GITHUB_OUTPUT
          echo "new_tag=${{ steps.create_release.outputs.new_release_git_tag }}" >> $GITHUB_OUTPUT
          echo "release_notes=${{ steps.create_release.outputs.new_release_notes }}" >> $GITHUB_OUTPUT
